import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-row space-x-4">
          <div className="flex flex-col">
            Image with tailwind wrapper
            <div>
              Image 1
              <Image
                src={
                  "https://firebasestorage.googleapis.com/v0/b/vent-d1d85.appspot.com/o/eventsPics%2FupcomingEvent1.jpg?alt=media&token=10198312-383d-4eef-af93-1f42671a17ff"
                }
                width={100}
                height={100}
              />
            </div>
            <div>
              Image 2
              <Image
                src={
                  "https://firebasestorage.googleapis.com/v0/b/vent-d1d85.appspot.com/o/eventsPics%2FupcomingEvent2.jpg?alt=media&token=6830d9a3-c32b-4f38-b2c4-96cec4011236"
                }
                width={100}
                height={100}
              />
            </div>
          </div>
          <div className="flex flex-col">
            Image without tailwind wrapper; but with Props value
            <div>
              Image 3
              <Image
                src={
                  "https://firebasestorage.googleapis.com/v0/b/vent-d1d85.appspot.com/o/eventsPics%2FupcomingEvent3.jpg?alt=media&token=f0bfdf4f-73b1-4ba8-a1cb-af503b5a0829"
                }
                width={100}
                height={100}
              />
            </div>
            <div>
              Image 4
              <Image
                src={
                  "https://firebasestorage.googleapis.com/v0/b/vent-d1d85.appspot.com/o/eventsPics%2FupcomingEvent4.jpg?alt=media&token=9bae0760-9424-49c1-903e-bb357d111a60"
                }
                width={100}
                height={100}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
